// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.15.8
// source: median_plugin_config.proto

package median

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MedianPluginConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AlphaPpb uint64 `protobuf:"varint,1,opt,name=alpha_ppb,json=alphaPpb,proto3" json:"alpha_ppb,omitempty"`
	DeltaC   uint64 `protobuf:"varint,2,opt,name=delta_c,json=deltaC,proto3" json:"delta_c,omitempty"`
}

func (x *MedianPluginConfig) Reset() {
	*x = MedianPluginConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_median_plugin_config_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MedianPluginConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MedianPluginConfig) ProtoMessage() {}

func (x *MedianPluginConfig) ProtoReflect() protoreflect.Message {
	mi := &file_median_plugin_config_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MedianPluginConfig.ProtoReflect.Descriptor instead.
func (*MedianPluginConfig) Descriptor() ([]byte, []int) {
	return file_median_plugin_config_proto_rawDescGZIP(), []int{0}
}

func (x *MedianPluginConfig) GetAlphaPpb() uint64 {
	if x != nil {
		return x.AlphaPpb
	}
	return 0
}

func (x *MedianPluginConfig) GetDeltaC() uint64 {
	if x != nil {
		return x.DeltaC
	}
	return 0
}

var File_median_plugin_config_proto protoreflect.FileDescriptor

var file_median_plugin_config_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x6e, 0x5f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x5f,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x2f, 0x63, 0x68,
	0x61, 0x69, 0x6e, 0x6c, 0x69, 0x6e, 0x6b, 0x2e, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2e, 0x72,
	0x65, 0x70, 0x6f, 0x72, 0x74, 0x69, 0x6e, 0x67, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x6d,
	0x65, 0x64, 0x69, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x22, 0x4a, 0x0a,
	0x12, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x6e, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x5f, 0x70, 0x70, 0x62,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x50, 0x70, 0x62,
	0x12, 0x17, 0x0a, 0x07, 0x64, 0x65, 0x6c, 0x74, 0x61, 0x5f, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x06, 0x64, 0x65, 0x6c, 0x74, 0x61, 0x43, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2e, 0x2f,
	0x6d, 0x65, 0x64, 0x69, 0x61, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_median_plugin_config_proto_rawDescOnce sync.Once
	file_median_plugin_config_proto_rawDescData = file_median_plugin_config_proto_rawDesc
)

func file_median_plugin_config_proto_rawDescGZIP() []byte {
	file_median_plugin_config_proto_rawDescOnce.Do(func() {
		file_median_plugin_config_proto_rawDescData = protoimpl.X.CompressGZIP(file_median_plugin_config_proto_rawDescData)
	})
	return file_median_plugin_config_proto_rawDescData
}

var file_median_plugin_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_median_plugin_config_proto_goTypes = []interface{}{
	(*MedianPluginConfig)(nil), // 0: chainlink.cosmos.reportingplugin.median.v1beta1.MedianPluginConfig
}
var file_median_plugin_config_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_median_plugin_config_proto_init() }
func file_median_plugin_config_proto_init() {
	if File_median_plugin_config_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_median_plugin_config_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MedianPluginConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_median_plugin_config_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_median_plugin_config_proto_goTypes,
		DependencyIndexes: file_median_plugin_config_proto_depIdxs,
		MessageInfos:      file_median_plugin_config_proto_msgTypes,
	}.Build()
	File_median_plugin_config_proto = out.File
	file_median_plugin_config_proto_rawDesc = nil
	file_median_plugin_config_proto_goTypes = nil
	file_median_plugin_config_proto_depIdxs = nil
}
